# Generated by Django 5.2 on 2025-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_category_description_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
